# Generated by Django 2.1.2 on 2018-10-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('slug', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('web', models.CharField(max_length=255, unique=True)),
                ('android_primary', models.CharField(max_length=255, unique=True)),
                ('android_fallback', models.CharField(max_length=255, unique=True)),
                ('ios_primary', models.CharField(max_length=255, unique=True)),
                ('ios_fallback', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
