# Generated by Django 2.1.2 on 2018-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkShortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Links'},
        ),
        migrations.AlterField(
            model_name='links',
            name='android_fallback',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='links',
            name='android_primary',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='links',
            name='ios_fallback',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='links',
            name='ios_primary',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='links',
            name='web',
            field=models.CharField(max_length=255),
        ),
    ]
