# Generated by Django 2.1.2 on 2018-10-26 17:58

import LinkShortner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkShortner', '0002_auto_20181026_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='slug',
            field=models.CharField(default=LinkShortner.models.Links.generate_slug, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
